import { CHAIN_ID } from "../../shared/constants/chain";

export enum ALCHEMY_CHAIN {
  SONEIUM_MAINNET = 'SONEIUM_MAINNET',
  SONIC_MAINNET = 'SONIC_MAINNET',
}

export const CHAIN_ID_BY_ALCHEMY_CHAIN: Record<ALCHEMY_CHAIN, CHAIN_ID> = {
  [ALCHEMY_CHAIN.SONEIUM_MAINNET]: CHAIN_ID.SONEIUM,
  [ALCHEMY_CHAIN.SONIC_MAINNET]: CHAIN_ID.SONIC,
};
