apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkada-core
  labels:
    app: arkada-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: arkada-core
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: arkada-core
    spec:
      containers:
        - name: arkada-core
          image: your-registry/arkada-core:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: arkada-secrets
                  key: database_url
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: arkada-secrets
                  key: session_secret
            - name: CORE_PORT
              value: '3000'
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
