apiVersion: v1
kind: Service
metadata:
  name: arkada-core
spec:
  type: NodePort
  selector:
    app: arkada-core
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 3001
