# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build core`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t core`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000
# Stage 1: Build
FROM docker.io/node:lts-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build:all

# Stage 2: Final image
FROM docker.io/node:lts-alpine

WORKDIR /app

RUN addgroup --system core && adduser --system -G core core

COPY --from=builder /app/dist/apps/core core/

COPY . core/
RUN chown -R core:core .

RUN npm --prefix core install --legacy-peer-deps --omit=dev

CMD [ "node", "core/main.js" ]
