name: Rollback Staging

on:
  workflow_dispatch:

jobs:
  rollback:
    name: Rollback to Previous Version
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_SSH_KEY }}
          known_hosts: ${{ secrets.STAGING_KNOWN_HOSTS }}

      - name: Rollback to previous image on Staging
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} \
          "echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin && \
          docker pull '${{ secrets.DOCKER_USERNAME }}/arkada-core:previous' && \
          docker stop core-dev || true && \
          docker rm core-dev || true && \
          docker run --network host --restart=always -d \
            --name core-dev \
            --env-file /home/core-dev.env \
            '${{ secrets.DOCKER_USERNAME }}/arkada-core:previous'"
